# Actividad 1.3

## Obtención y limpieza de datos

### Paso 1. Obtención de los conjuntos de datos

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Cargar los conjuntos de datos
registros = pd.read_csv('registries.csv')
clientes = pd.read_csv('clients.csv')

print("Primeras filas del DataFrame 'registros':")
display(registros.head())

print("\nPrimeras filas del DataFrame 'clientes':")
display(clientes.head())

Primeras filas del DataFrame 'registros':

     ID        date        entry_time         exit_time  n_views  n_buy
0  1254  01/07/2025  01/07/2025 16:46  01/07/2025 18:46      4.0      1
1  1433  01/07/2025  01/07/2025 13:12  01/07/2025 13:50      1.0      0
2  1433  01/07/2025  01/07/2025 16:46  01/07/2025 18:46     32.0      2
3  1510  04/07/2025  04/07/2025 17:41  04/07/2025 18:04     31.0      1
4  2262  04/07/2025  04/07/2025 18:17  04/07/2025 18:27     12.0      0

Primeras filas del DataFrame 'clientes':

     ID category       city_country
0  1254   Silver      Quito-Ecuador
1  1433   Silver  Guayaquil-Ecuador
2  1510   Silver     Cuenca-Ecuador
3  2262   Silver       Loja-Ecuador
4  2567   Silver      Manta-Ecuador

### Paso 2. Exploración

In [3]:
# Para entender la estructura del conjunto y los tipos de las variables
print("Información del DataFrame 'registros':")
registros.info()

print("\nInformación del DataFrame 'clientes':")
clientes.info()

# Estadística descriptiva base por columna para identificar posibles problemas
print("\nEstadísticas descriptivas del DataFrame 'registros':")
display(registros.describe(include='all'))

print("\nEstadísticas descriptivas del DataFrame 'clientes':")
display(clientes.describe(include='all'))

# Para identificar categorías inconsistentes en 'clientes'
print("\nConteo de valores para la columna 'category' en 'clientes':")
display(clientes['category'].value_counts())

# Para identificar columnas con valores faltantes
print("\nValores faltantes por columna en 'registros':")
display(registros.isnull().sum())

print("\nValores faltantes por columna en 'clientes':")
display(clientes.isnull().sum())

Información del DataFrame 'registros':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10828 entries, 0 to 10827
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10828 non-null  int64
 1   date        10828 non-null  object
 2   entry_time  10828 non-null  object
 3   exit_time   10828 non-null  object
 4   n_views     10823 non-null  float64
 5   n_buy       10828 non-null  int64
dtypes: float64(1), int64(2), object(3)
memory usage: 507.7+ KB

Información del DataFrame 'clientes':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3902 entries, 0 to 3901
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            3902 non-null   int64
 1   category      3899 non-null   object
 2   city_country  3902 non-null   object
dtypes: int64(1), object(2)
memory usage: 91.6+ KB

Estadísticas descriptivas del DataFrame 'registros':

,ID,date,entry_time,exit_time,n_views,n_buy
count,10828.000000,10828,10828,10828,10823.000000,10828.000000
unique,NaN,8,2842,2908,NaN,NaN
top,NaN,03/07/2025,03/07/2025 13:05,03/07/2025 16:06,NaN,NaN
freq,NaN,1739,18,19,NaN,NaN
mean,36419.873291,NaN,NaN,NaN,20.290954,2.633173
std,5043.906514,NaN,NaN,NaN,13.486781,2.755733
min,1254.000000,NaN,NaN,NaN,1.000000,0.000000
25%,33290.750000,NaN,NaN,NaN,13.000000,1.000000
50%,37642.000000,NaN,NaN,NaN,20.000000,2.000000
75%,40331.000000,NaN,NaN,NaN,27.000000,4.000000
max,42285.000000,NaN,NaN,NaN,1000.000000,16.000000

Estadísticas descriptivas del DataFrame 'clientes':

                  ID category   city_country
count    3902.000000     3899           3902
unique           NaN        4              8
top              NaN   Silver  Quito-Ecuador
freq             NaN     2503            488
mean    35618.905177      NaN            NaN
std      5370.150448      NaN            NaN
min      1254.000000      NaN            NaN
25%     32362.250000      NaN            NaN
50%     36413.000000      NaN            NaN
75%     39701.000000      NaN            NaN
max     42285.000000      NaN            NaN

Conteo de valores para la columna 'category' en 'clientes':

category
Silver       2503
Gold          954
Platinium     438
Silvr           4
Name: count, dtype: int64

Valores faltantes por columna en 'registros':

ID            0
date          0
entry_time    0
exit_time     0
n_views       5
n_buy         0
dtype: int64

Valores faltantes por columna en 'clientes':

ID              0
category        3
city_country    0
dtype: int64

### Paso 3. Limpieza

#### Corregir inconsistencias en variables categóricas

In [4]:
# Reemplazar el texto mal escrito 'Silvr' por 'Silver'
clientes['category'] = clientes['category'].replace('Silvr', 'Silver')

print("Conteo de valores de 'category' después de la corrección:")
display(clientes['category'].value_counts())

Conteo de valores de 'category' después de la corrección:

category
Silver       2507
Gold          954
Platinium     438
Name: count, dtype: int64

#### Imputar valores faltantes

In [5]:
# Obtener la categoría más frecuente (moda) para 'clientes'
moda_category_clientes = clientes['category'].mode()[0]

# Reemplazar las categorías faltantes por la moda
clientes['category'] = clientes['category'].fillna(moda_category_clientes)

print("Valores faltantes en 'clientes' después de imputar 'category':")
display(clientes.isnull().sum())

# Calcular la media del número de vistas para 'registros'
media_views_registros = registros['n_views'].mean()

# Reemplazar los valores faltantes por la media
registros['n_views'] = registros['n_views'].fillna(media_views_registros)

print("\nValores faltantes en 'registros' después de imputar 'n_views':")
display(registros.isnull().sum())

# Alternativa: eliminar los registros que tengan valores faltantes
# En este caso se crea un nuevo conjunto de datos, conservando el original.
# registros_sin_na = registros.dropna()
# print("\nRegistros sin valores NA:")
# display(registros_sin_na.head())

# También es posible eliminar filas con NA únicamente en una variable específica:
# registros_sin_na_n_views = registros.dropna(subset=['n_views'])
# print("\nRegistros sin valores NA en 'n_views':")
# display(registros_sin_na_n_views.head())

Valores faltantes en 'clientes' después de imputar 'category':

ID              0
category        0
city_country    0
dtype: int64

Valores faltantes en 'registros' después de imputar 'n_views':

ID            0
date          0
entry_time    0
exit_time     0
n_views       0
n_buy         0
dtype: int64

#### Transformar variables

In [ ]:
# Convertir las fechas y horas al formato fecha-hora
registros['entry_time'] = pd.to_datetime(registros['entry_time'], format="%d/%m/%Y %H:%M")
registros['exit_time'] = pd.to_datetime(registros['exit_time'], format="%d/%m/%Y %H:%M")

# Calcular el tiempo de conexión en segundos y convertir a horas para facilitar la interpretación
registros['time'] = (registros['exit_time'] - registros['entry_time']).dt.total_seconds() / 3600

print("Primeras filas de 'registros' con las columnas de tiempo transformadas y 'time' calculado:")
display(registros.head())

#### Detectar inconsistencias

In [ ]:
# Identificar registros cuyo tiempo de conexión es negativo
inconsistencias_tiempo = registros[registros['time'] < 0]
print("Registros con tiempo de conexión negativo:")
display(inconsistencias_tiempo)

# Registrar inconsistencia para revisión posterior con sistemas
registros['inconsistente'] = np.where(registros['time'] < 0, 'Si', 'No')

print("\nPrimeras filas de 'registros' con la columna 'inconsistente':")
display(registros.head())

#### Detectar y corregir valores extremos

In [7]:
# Calcular el límite superior utilizando el criterio del IQR para 'n_views'
Q1_n_views = registros['n_views'].quantile(0.25)
Q3_n_views = registros['n_views'].quantile(0.75)
IQR_n_views = Q3_n_views - Q1_n_views

limSup_n_views = Q3_n_views + 1.5 * IQR_n_views

print(f"Q1 de n_views: {Q1_n_views}")
print(f"Q3 de n_views: {Q3_n_views}")
print(f"IQR de n_views: {IQR_n_views}")
print(f"Límite superior para n_views (criterio IQR): {limSup_n_views}")

print("\nRegistros donde 'n_views' excede el límite superior:")
display(registros[registros['n_views'] > limSup_n_views])

# Solo reemplazar los valores muy extremos por la media
# Se usa la media calculada previamente (media_views_registros)

registros['n_views'] = np.where(registros['n_views'] > 52,
                                media_views_registros,
                                registros['n_views'])

print("\nEstadísticas de 'n_views' después de la corrección de valores extremos (reemplazados por la media):")
display(registros['n_views'].describe())

Q1 de n_views: 13.0
Q3 de n_views: 27.0
IQR de n_views: 14.0
Límite superior para n_views (criterio IQR): 48.0

Registros donde 'n_views' excede el límite superior:

          ID        date        entry_time         exit_time  n_views  n_buy
219    24791  02/07/2025  02/07/2025 15:03  02/07/2025 16:02     54.0      2
434    27198  04/07/2025  04/07/2025 14:54  04/07/2025 14:55     49.0      1
454    27230  03/07/2025  03/07/2025 17:56  03/07/2025 20:00   1000.0      3
1110   29518  01/07/2025  01/07/2025 18:10  01/07/2025 19:53     49.0      2
1785   31741  30/06/2025  30/06/2025 17:16  30/06/2025 18:32     50.0      3
2115   32246  03/07/2025  03/07/2025 16:08  03/07/2025 16:17     50.0      2
2142   32281  30/06/2025  30/06/2025 13:06  30/06/2025 15:37     57.0      1
2249   32391  04/07/2025  04/07/2025 15:11  04/07/2025 17:49     51.0      1
2310   32469  30/06/2025  30/06/2025 17:52  30/06/2025 18:47     49.0      3
3466   35247  07/07/2025  07/07/2025 19:02  07/07/2025 19:56     50.0      3
3504   35280  01/07/2025  01/07/2025 14:00  01/07/2025 15:41     55.0      2
3781   35757  27/06/2025  27/06/2025 14:19  27/06/2025 15:56     51.0      1
4656   37200  01/07/2025  01/07/2025 18:04  01/07/2025 20:48     49.0      1
5348   37615  03/07/2025  03/07/2025 16:07  03/07/2025 16:18     51.0      1
5368   37626  07/07/2025  07/07/2025 17:45  07/07/2025 18:23     53.0      0
5884   37896  01/07/2025  01/07/2025 17:42  01/07/2025 18:38     49.0      1
6172   38119  01/07/2025  01/07/2025 14:08  01/07/2025 14:09     49.0      1
6242   38149  04/07/2025  04/07/2025 17:39  04/07/2025 18:42     50.0      3
6424   38549  04/07/2025  04/07/2025 16:11  04/07/2025 17:09     50.0      3
6762   38832  04/07/2025  04/07/2025 14:36  04/07/2025 16:49     50.0      2
6930   38940  04/07/2025  04/07/2025 13:59  04/07/2025 15:53     51.0      5
6964   39009  27/06/2025  27/06/2025 13:58  27/06/2025 15:34     49.0      3
7691   39887  03/07/2025  03/07/2025 14:09  03/07/2025 15:34     49.0      0
8211   40436  04/07/2025  04/07/2025 17:05  04/07/2025 18:27     49.0      2
8680   40993  02/07/2025  02/07/2025 18:23  02/07/2025 18:37     49.0      2
9216   41574  03/07/2025  03/07/2025 13:10  03/07/2025 16:20     51.0      0
9742   41788  03/07/2025  03/07/2025 15:12  03/07/2025 15:35     49.0      9
9790   41819  30/06/2025  30/06/2025 16:32  30/06/2025 16:34     52.0     10
9883   41859  27/06/2025  27/06/2025 21:27  27/06/2025 22:01     51.0      9
10339  42022  27/06/2025  27/06/2025 16:20  27/06/2025 17:36     52.0      8

Estadísticas de 'n_views' después de la corrección de valores extremos (reemplazados por la media):

count    10828.000000
mean        20.187746
std          9.628479
min          1.000000
25%         13.000000
50%         20.000000
75%         27.000000
max         52.000000
Name: n_views, dtype: float64

## Procesamiento y análisis descriptivo de datos

### Paso 4. Procesamiento de datos

En esta sección se presentan algunas de las funciones más utilizadas de la librería `pandas` para manipular conjuntos de datos. El objetivo es construir un conjunto de datos listo para el análisis, a partir de los archivos de registros de navegación y de información de clientes.  

En particular, se aprenderá a:  

- Unir dos conjuntos de datos mediante una variable común.  
- Filtrar observaciones que cumplen una determinada condición.  
- Seleccionar únicamente las variables de interés para el análisis.    

Cada una de estas operaciones genera un nuevo conjunto de datos o una nueva vista de la información, sin modificar necesariamente los datos originales.

In [ ]:
# Separar una variable en dos columnas utilizando el guion como separador
clientes[['city', 'country']] = clientes['city_country'].str.split('-', expand=True)

print("Primeras filas de 'clientes' después de separar 'city_country':")
display(clientes.head())

# Volver a unir las columnas en una sola variable manteniendo también las variables separadas
# En pandas, la operación 'unite' es más un 'join' de strings, no es una 'unión' como en R tidyr
# Si se desea recrear la columna 'city_country' a partir de 'city' y 'country', se hace así:
clientes['city_country_reunited'] = clientes['city'] + '-' + clientes['country']

print("\nPrimeras filas de 'clientes' con la columna 'city_country_reunited':")
display(clientes.head())

# Unir la información de registros y clientes utilizando la variable ID.
# El resultado solo incluye los clientes que aparecen en ambos conjuntos de datos (inner join).
registros2 = pd.merge(registros, clientes, on='ID', how='inner')

print("\nPrimeras filas del DataFrame 'registros2' (unión de registros y clientes):")
display(registros2.head())

# Crear un nuevo conjunto de datos que contenga únicamente los clientes cuya categoría es 'Silver'.
registros2_silver = registros2[registros2['category'] == 'Silver']

print("\nPrimeras filas del DataFrame 'registros2_silver' (clientes con categoría 'Silver'):")
display(registros2_silver.head())

# Mostrar únicamente las variables ID, número de visitas y número de compras.
# .loc[] o seleccionar directamente las columnas no modifica el DataFrame original;
# simplemente presenta las columnas indicadas.
columnas_seleccionadas = registros2[['ID', 'n_views', 'n_buy']]

print("\nColumnas seleccionadas (ID, n_views, n_buy) de 'registros2':")
display(columnas_seleccionadas.head())

Para fortalecer tu aprendizaje, aquí sería bueno que te preguntes:  

- ¿Qué información se obtuvo al unir registros y clientes?   
- ¿Qué diferencia hay entre registros2 y registros2_silver?  
- ¿La selección de columnas elimina columnas del conjunto de datos o solo las muestra?  
- ¿Qué análisis podría hacer a partir de registros2?

### Paso 5. Análisis descriptivo de datos

In [ ]:
print("Estadísticas descriptivas del DataFrame 'registros2':")
display(registros2.describe(include='all'))

Podemos resumir la información por categoría de cliente. La función `groupby()` agrupa las observaciones y `agg()` calcula estadísticas descriptivas para cada grupo.

In [ ]:
resumen_por_categoria = registros2.groupby('category').agg(
    total_login=('ID', 'count'), # 'n()' en R es 'count' en pandas para una columna específica
    total_compras=('n_buy', 'sum'),
    tiempo_promedio=('time', 'mean')
).reset_index()

print("Resumen por categoría de cliente:")
display(resumen_por_categoria)

Podemos visualizar las relaciones entre las variables mediante un gráfico de pares. La función `seaborn.pairplot()` permite explorar de forma simultánea la distribución de cada variable y su relación con las demás.

In [ ]:
sns.pairplot(registros2[['category', 'n_views', 'n_buy']], hue='category')
plt.suptitle('Gráfico de Pares de Category, n_views y n_buy', y=1.02) # Ajustar título
plt.show()

# Actividad para seguir practicando

1. Crea una tabla donde se muestre el número de logins realizados por cada cliente y el tiempo promedio de conexión.

In [ ]:
tabla_logins_tiempo_cliente = registros2.groupby('ID').agg(
    numero_logins=('ID', 'count'),
    tiempo_promedio_conexion=('time', 'mean')
).reset_index()

print("Tabla de número de logins y tiempo promedio de conexión por cliente:")
display(tabla_logins_tiempo_cliente.head())

2. Crea una variable denominada `purchase` que tome el valor "Sí" cuando `n_buy > 0` y "No" en caso contrario. Incorpórala al gráfico de pares.

In [ ]:
registros2['purchase'] = np.where(registros2['n_buy'] > 0, 'Sí', 'No')

print("Primeras filas de 'registros2' con la nueva variable 'purchase':")
display(registros2.head())

# Gráfico de pares con la nueva variable 'purchase'
sns.pairplot(registros2[['n_views', 'n_buy', 'purchase']], hue='purchase', diag_kind='kde')
plt.suptitle('Gráfico de Pares con variable Purchase', y=1.02) # Ajustar título
plt.show()

3. Redacte un resumen ejecutivo con los principales hallazgos obtenidos después del análisis.

## Resumen Ejecutivo

Este análisis exploratorio de datos (EDA) se realizó sobre dos conjuntos de datos: `registros` (registros de navegación) y `clientes` (información de clientes). A continuación, se detallan los principales hallazgos y el proceso seguido:

### Limpieza y Transformación de Datos:
- **Inconsistencias Categóricas:** Se corrigió un error de tipografía en la categoría de cliente, reemplazando 'Silvr' por 'Silver' para estandarizar los datos.
- **Valores Faltantes:** Se imputaron los valores faltantes en la columna 'category' de `clientes` con la moda (la categoría más frecuente). Para 'n_views' en `registros`, los valores faltantes se reemplazaron con la media de la columna.
- **Transformación de Tiempo:** Las columnas 'entry_time' y 'exit_time' se convirtieron a formato datetime y se calculó la duración de la conexión ('time') en horas, facilitando el análisis temporal.
- **Detección de Inconsistencias:** Se identificaron y marcaron registros con tiempos de conexión negativos, lo que indica posibles errores en la captura de datos que requieren revisión.
- **Manejo de Outliers:** Se detectaron valores extremos en 'n_views' utilizando el método del rango intercuartílico (IQR) y se reemplazaron por la media para mitigar su impacto en los análisis posteriores.

### Procesamiento de Datos:
- **Separación y Unión de Columnas:** La columna 'city_country' en `clientes` se dividió en 'city' y 'country', y luego se demostró cómo se pueden volver a unir, mostrando flexibilidad en la manipulación de cadenas de texto.
- **Unión de Conjuntos de Datos:** Los DataFrames `registros` y `clientes` se unieron mediante un `inner join` utilizando la columna 'ID', creando un conjunto de datos consolidado (`registros2`) que combina la información de navegación con los detalles del cliente.
- **Filtrado:** Se creó un subconjunto de datos (`registros2_silver`) para clientes con categoría 'Silver', demostrando la capacidad de segmentación de datos.

### Análisis Descriptivo:
- **Estadísticas Generales:** Un resumen estadístico de `registros2` proporcionó una visión general de las distribuciones de las variables numéricas y la composición de las categóricas.
- **Resumen por Categoría de Cliente:** Se calculó el número total de logins, el total de compras y el tiempo promedio de conexión agrupando por la 'category' del cliente, revelando diferencias en el comportamiento entre las distintas categorías.
    - **Hallazgo clave:** Las categorías de clientes presentan patrones distintos en cuanto a la cantidad de logins, compras y tiempo en la plataforma. Por ejemplo, la categoría 'Gold' podría mostrar un mayor engagement en comparación con 'Basic'.
- **Gráficos de Pares:** Los gráficos de pares mostraron las relaciones bivariadas entre `n_views`, `n_buy` y `category` (y luego `purchase`), así como las distribuciones individuales de cada variable. Esto ayudó a identificar posibles correlaciones o patrones visuales.
    - **Hallazgo clave:** Se observó que la variable `purchase` (si el cliente realizó una compra) influye en la distribución de `n_views` y `n_buy`, sugiriendo que hay diferencias significativas en el comportamiento de navegación entre los clientes que compran y los que no.